### PR TITLE
Adds POST form data parsing

### PR DESCRIPTION
**Pull request by jessepollak**
And fixes a old bug

### CODE REVIEW

**Comment by jessepollak** [comment]
OK, so I added basic POST form data parsing.

# Decision Decisions
1. I was conflicted as to whether I should write the parsing myself or use a library, but I ultimately went with a library (although, I've left the start of my code commented out). I know this is "Simple API," so I'll defer to you on this one. I mainly went with a library because their are some security concerns around parsing POST data, which I haven't fully dug into.
2. I added a meta field to the response of the Controller.checkRoute function. Before, this was just returning the function to call. Now, it's returning the function to call (handler) and all of the meta information for the route (method type). I'm not sure if this is the best place to do this, but it was the only place that made sense. Really, I think that the checkRoute function should be renamed and split up, but that's a longer discussion.

Would love to hear thoughts etc.

**Comment by josephwegner** [comment]
I support using formidable.  There are very real security concerns that I also am not interested in thinking about.

However there is one little thing here that makes me nervous.  Your code right now will only parse POST bodies.  What about PUT?  Or SOMESTUPIDCUSTOMHTTPMETHOD.  I think that if we're going to automatically parse request bodies, we need to always do it.  Or at least always give an option.

What does Formidable do if you pass it something without a request body?  If we can't do that, we can revisit doing this manually - req.on('end') will always get called, even if there is no request body.

**Comment by jessepollak** [comment]
I can change it to always parse the data. Lots of frameworks do this, so I'm not really concerned about the performance implications. If we want to, we could also add an option to disable automatic parsing. Alternatively, we could build this as a middleware, similar to the Express middleware stack.

**Comment by josephwegner** [comment]
Let's do that - always parse the data.  When I think about what is most "simple" for the developer, that's probably it.

**Comment by jessepollak** [comment]
OK, I'm going to always parse for now and then eventually get to the option to turn off.

**Comment by jessepollak** [comment]
Just a heads up that I also added a development dependency (the request library) to make testing easier.

**Pull request merged**
